### PR TITLE
Page with sectioning

### PR DESCRIPTION
**Pull request by AHPender**

### CODE REVIEW

**Comment by tkraak** [comment]
Hey Abigail - please submit the pull request from your "feature" branch into master. Let me know if you don't know what any of this means :)

**Comment by AHPender** [comment]
Ok, I'll try it now. This is to change it from the gh-status to the regular
master THEN do a pull request to you? correct?


On Thu, Feb 25, 2016 at 10:26 AM, Tom Kraak <notifications@github.com>
wrote:

> Hey Abigail - please submit the pull request from your "feature" branch
> into master. Let me know if you don't know what any of this means :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/betamore/fewd-html-exercise-1/pull/13#issuecomment-188839133>
> .
>



-- 
*Abigail Pendergrass*

**Comment by AHPender** [comment]
Please let me know if this is correct. When I went into my Master to do a
new Pull request it said there were no comparisons available. It suggested
I change the *base *and that allowed me to make a Pull request to the
Exercise 1.

On Thu, Feb 25, 2016 at 10:32 AM, Abigail Pendergrass <
pendergrass.abigail@gmail.com> wrote:

> Ok, I'll try it now. This is to change it from the gh-status to the
> regular master THEN do a pull request to you? correct?
>
>
> On Thu, Feb 25, 2016 at 10:26 AM, Tom Kraak <notifications@github.com>
> wrote:
>
>> Hey Abigail - please submit the pull request from your "feature" branch
>> into master. Let me know if you don't know what any of this means :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/betamore/fewd-html-exercise-1/pull/13#issuecomment-188839133>
>> .
>>
>
>
>
> --
> *Abigail Pendergrass*
>



-- 
*Abigail Pendergrass*

**Comment by tkraak** [comment]
Can you get on Slack to discuss?

**Pull request closed without merging**
