### PR TITLE
HTML Exercise Potential Final

### PR DESCRIPTION
**Pull request by kmundle**
I found this to be difficult because there is only so much we can do via HTML. Let me know if this is what you wanted. If not, I can make modifications.

### CODE REVIEW

**Comment by tkraak** [comment]
_There is only so much we can do via HTML_ ... exactly, that's one of the main lessons learned here 😎.

You did very well, just "close out" the document properly so it's valid HTML(5).

**Comment by kmundle** [comment]
I realized I also forgot to close out the body as well! So, I believe I'm all set now.

**Comment by tkraak** [comment]
Where does your `<section>` close? And what's the purpose of the `<div>` around `<article>`?

**Comment by kmundle** [comment]
I guess I was under the impression that div was helpful, but if article is the only element within it, the delineation doesn't do anything- it's already set apart. That makes sense. I removed <div>, closed the <section> and reviewed one more time.

**Pull request merged**
